import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { randomBytes, randomUUID } from 'node:crypto';
import path from 'node:path';
import { db, content } from './db.js';
import { passwordHash,passwordMatches,hashToken } from './auth.js';
const app=express();
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:{directives:{'img-src':["'self'",'https:','data:'],'script-src':["'self'"],'style-src':["'self'","'unsafe-inline'"],'upgrade-insecure-requests':process.env.NODE_ENV==='production'?[]:null}}}));
app.use(express.json({limit:'150kb'}));
app.use('/api',rateLimit({windowMs:60000,max:180}));
app.use('/api',(req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)return res.status(403).json({error:'مبدأ درخواست معتبر نیست.'});next();});
if(!db.prepare("SELECT value FROM config WHERE key='password'").get()&&process.env.ADMIN_PASSWORD?.length>=12)db.prepare("INSERT INTO config VALUES ('password',?)").run(passwordHash(process.env.ADMIN_PASSWORD));
function auth(req,res,next){const token=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8);if(!token||!db.prepare('SELECT 1 FROM sessions WHERE token=? AND expires>?').get(hashToken(token),Date.now()))return res.status(401).json({error:'ابتدا وارد پنل شوید.'});next();}
const limited=rateLimit({windowMs:15*60000,max:15,message:{error:'درخواست‌های زیادی ارسال شده است. کمی بعد دوباره تلاش کنید.'}});
app.get('/api/content',(req,res)=>res.json(content(true)));
app.post('/api/login',limited,(req,res)=>{const {username,password}=req.body;const hash=db.prepare("SELECT value FROM config WHERE key='password'").get()?.value;if(typeof password!=='string'||password.length>256||username!==(process.env.ADMIN_USERNAME||'admin')||!passwordMatches(password,hash))return res.status(401).json({error:'نام کاربری یا رمز عبور نادرست است.'});const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES (?,?)').run(hashToken(token),Date.now()+8*3600000);res.cookie('session',token,{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:8*3600000});res.json({ok:true});});
app.post('/api/logout',(req,res)=>{const token=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8);if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(hashToken(token));res.clearCookie('session');res.json({ok:true});});
app.get('/api/admin',auth,(req,res)=>res.json({...content(),requests:db.prepare('SELECT * FROM requests ORDER BY created DESC').all().map(x=>({...x,...JSON.parse(x.value)})),certificates:db.prepare('SELECT * FROM certificates ORDER BY rowid DESC').all()}));
const kinds=['services','products','courses','posts','pages','gallery','licenses','settings'];
app.put('/api/admin/content/:kind/:id',auth,(req,res)=>{const {kind,id}=req.params;const value=req.body;if(!kinds.includes(kind)||!/^[a-z0-9-]{1,80}$/.test(id)||typeof value!=='object'||!value||Array.isArray(value))return res.status(400).json({error:'محتوا معتبر نیست.'});if(kind!=='settings'&&(!value.title?.trim()||value.title.length>200))return res.status(400).json({error:'عنوان الزامی است.'});if(value.image&&!/^\/(?!\/)|^https:\/\//.test(value.image))return res.status(400).json({error:'نشانی تصویر باید داخلی یا HTTPS باشد.'});if(kind==='products'&&(!Number.isSafeInteger(value.price)||value.price<0||!Number.isSafeInteger(value.stock)||value.stock<0))return res.status(400).json({error:'قیمت و موجودی معتبر وارد کنید.'});db.prepare('INSERT OR REPLACE INTO content VALUES (?,?,?)').run(kind,id,JSON.stringify({...value,id}));res.json({ok:true});});
app.delete('/api/admin/content/:kind/:id',auth,(req,res)=>{if(!kinds.includes(req.params.kind)||req.params.kind==='settings')return res.sendStatus(400);db.prepare('DELETE FROM content WHERE kind=? AND id=?').run(req.params.kind,req.params.id);res.json({ok:true});});
app.post('/api/requests',limited,(req,res)=>{const {kind,name,phone,message='',email='',course='',items=[],address='',consent}=req.body;if(!['contact','service','enrollment','career','order'].includes(kind)||typeof name!=='string'||name.trim().length<2||name.length>100||typeof phone!=='string'||!/^09\d{9}$/.test(phone)||typeof message!=='string'||message.length>10000||consent!==true)return res.status(400).json({error:'نام، موبایل معتبر و پذیرش شرایط الزامی است.'});let details={name:name.trim(),phone,message,email};if(kind==='enrollment'){const item=content(true).courses.find(x=>x.id===course);if(!item)return res.status(400).json({error:'دوره یافت نشد.'});details.course=item.title;}
 if(kind==='order'){if(!Array.isArray(items)||!items.length||items.length>30||typeof address!=='string'||address.trim().length<10)return res.status(400).json({error:'سبد خرید و نشانی را تکمیل کنید.'});const products=content(true).products;const seen=new Set();const lines=[];for(const line of items){const p=products.find(x=>x.id===line.id);if(!p||seen.has(line.id)||!Number.isInteger(line.quantity)||line.quantity<1||line.quantity>p.stock)return res.status(400).json({error:'موجودی یک محصول کافی نیست. سبد را بررسی کنید.'});seen.add(line.id);lines.push({id:p.id,title:p.title,price:p.price,quantity:line.quantity});}details={...details,items:lines,total:lines.reduce((s,x)=>s+x.price*x.quantity,0),address};}
 const id='MV-'+randomBytes(6).toString('hex').toUpperCase();db.prepare('INSERT INTO requests (id,kind,value,created) VALUES (?,?,?,?)').run(id,kind,JSON.stringify(details),new Date().toISOString());res.status(201).json({id});});
app.post('/api/track',limited,(req,res)=>{const row=db.prepare('SELECT * FROM requests WHERE id=?').get(String(req.body.id||'').toUpperCase());if(!row||JSON.parse(row.value).phone!==req.body.phone)return res.status(404).json({error:'درخواستی با این مشخصات پیدا نشد.'});res.json({id:row.id,status:row.status,created:row.created,kind:row.kind});});
app.patch('/api/admin/requests/:id',auth,(req,res)=>{if(!['جدید','در حال بررسی','تأیید شده','تکمیل شده','لغو شده'].includes(req.body.status))return res.sendStatus(400);const request=db.prepare('SELECT * FROM requests WHERE id=?').get(req.params.id);if(!request)return res.sendStatus(404);const previous=request.status;const next=req.body.status;const active=s=>['تأیید شده','تکمیل شده'].includes(s);try{db.exec('BEGIN IMMEDIATE');if(request.kind==='order'&&active(previous)!==active(next)){for(const line of JSON.parse(request.value).items){const row=db.prepare("SELECT value FROM content WHERE kind='products' AND id=?").get(line.id);if(!row)throw Error('محصول سفارش حذف شده است.');const p=JSON.parse(row.value);p.stock+=active(next)?-line.quantity:line.quantity;if(p.stock<0)throw Error('موجودی برای تأیید سفارش کافی نیست.');db.prepare("UPDATE content SET value=? WHERE kind='products' AND id=?").run(JSON.stringify(p),line.id);}}db.prepare('UPDATE requests SET status=? WHERE id=?').run(next,req.params.id);db.exec('COMMIT');res.json({ok:true});}catch(e){db.exec('ROLLBACK');res.status(400).json({error:e.message});}});
app.post('/api/admin/certificates',auth,(req,res)=>{const {name,course,date,confirmed}=req.body;if(!name?.trim()||!course?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(date)||confirmed!==true)return res.status(400).json({error:'اطلاعات و تأیید پایان آموزش الزامی است.'});const id='MVC-'+randomUUID().slice(0,8).toUpperCase();db.prepare('INSERT INTO certificates VALUES (?,?,?,?)').run(id,name.slice(0,100),course.slice(0,200),date);res.json({id});});
app.delete('/api/admin/certificates/:id',auth,(req,res)=>{db.prepare('DELETE FROM certificates WHERE id=?').run(req.params.id);res.json({ok:true});});
app.post('/api/verify',limited,(req,res)=>{const row=db.prepare('SELECT * FROM certificates WHERE id=? AND name=?').get(String(req.body.id||'').toUpperCase(),String(req.body.name||'').trim());if(!row)return res.status(404).json({error:'گواهی معتبر با این مشخصات یافت نشد.'});res.json(row);});
app.use(express.static(path.resolve('dist')));
app.get('/{*path}',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'مسیر یافت نشد.'});res.sendFile(path.resolve('dist/index.html'));});
app.use((err,req,res,next)=>{console.error(err.message);res.status(500).json({error:'خطایی رخ داد. دوباره تلاش کنید.'});});
app.listen(process.env.PORT||3001,'0.0.0.0',()=>console.log(`Movasaq API running on port ${process.env.PORT||3001}`));
