import {useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ShoppingBag,ArrowUpLeft,Search,Plus,Minus,Trash2,ShieldCheck,Truck,PackageCheck} from 'lucide-react';
import {useSite,money} from '../context';
import {Button,PageHero,Empty,Notice} from '../components/UI';
import {RequestForm} from '../components/Forms';
import {NotFound} from './Content';
export function ProductCard({product:p}){const {addToCart}=useSite();return <article className="product-card"><Link className="product-image" to={'/store/'+p.id}><img src={p.image} alt={p.title} loading="lazy"/><span className="product-tag">{p.stock>0?'قابل سفارش':'ناموجود'}</span></Link><div className="product-body"><span className="eyebrow">{p.category}</span><Link to={'/store/'+p.id}><h3>{p.title}</h3></Link><p>{p.excerpt}</p><div className="product-bottom"><span><b>{money(p.price)}</b> <small>تومان</small></span><button aria-label={'افزودن '+p.title+' به سبد'} disabled={p.stock<1} onClick={()=>addToCart(p)}><Plus size={19}/></button></div></div></article>;}
export function Store(){const {data}=useSite();const [query,setQuery]=useState('');const [category,setCategory]=useState('همه');const [sort,setSort]=useState('default');let products=data.products.filter(p=>(category==='همه'||p.category===category)&&`${p.title} ${p.excerpt}`.includes(query));if(sort==='asc')products.sort((a,b)=>a.price-b.price);if(sort==='desc')products.sort((a,b)=>b.price-a.price);return <><PageHero title="مجهز برای مراقبت بهتر" eyebrow="فروشگاه موثق" description="تجهیزات ایمنی فردی، ملزومات مراقبتی و پوشاک حرفه‌ای"/><section className="container section"><div className="store-benefits"><span><ShieldCheck/> راهنمایی پیش از سفارش</span><span><PackageCheck/> بررسی موجودی و مشخصات</span><span><Truck/> هماهنگی تحویل با شما</span></div><div className="listing-toolbar"><div className="tabs">{['همه',...new Set(data.products.map(x=>x.category))].map(c=><button key={c} onClick={()=>setCategory(c)} className={category===c?'selected':''}>{c}</button>)}</div><div className="filter-controls"><label className="search-input"><Search size={17}/><input value={query} aria-label="جستجوی محصولات" placeholder="جستجوی محصول..." onChange={e=>setQuery(e.target.value)}/></label><select aria-label="مرتب‌سازی قیمت" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">مرتب‌سازی</option><option value="asc">ارزان‌ترین</option><option value="desc">گران‌ترین</option></select></div></div>{products.length?<div className="grid three">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<Empty text="محصولی با این مشخصات پیدا نشد."/>}<Notice>کاتالوگ اولیه و قیمت‌ها نمونه‌اند. ثبت سفارش برای بررسی موجودی، تأیید قیمت و هماهنگی تحویل است؛ پرداخت آنلاین انجام نمی‌شود.</Notice></section></>;}
export function ProductDetail(){const {id}=useParams();const {data,addToCart}=useSite();const p=data.products.find(x=>x.id===id);if(!p)return <NotFound/>;return <><PageHero title={p.title} eyebrow="فروشگاه تجهیزات"/><section className="container section split product-detail"><div className="product-detail-image"><img src={p.image} alt={p.title}/></div><div><span className="eyebrow">{p.category}</span><h2>{p.title}</h2><p>{p.body}</p><span className="stock-label">{p.stock>0?'قابل ثبت سفارش':'در حال حاضر ناموجود'}</span><div className="product-price">{money(p.price)} <small>تومان</small></div><div className="button-row"><Button disabled={!p.stock} onClick={()=>addToCart(p)}>افزودن به سبد خرید <ShoppingBag size={18}/></Button><Button to="/cart" variant="outline">مشاهده سبد</Button></div><Notice>قیمت و مدل نهایی پیش از تأیید سفارش توسط فروش بررسی می‌شود.</Notice></div></section></>;}
export function Cart(){const {data,cart,setCart}=useSite();const [checkout,setCheckout]=useState(false);const [submitted,setSubmitted]=useState(false);const lines=cart.map(x=>({...x,product:data.products.find(p=>p.id===x.id)}));const total=lines.reduce((sum,x)=>sum+(x.product?.price||0)*x.quantity,0);const invalid=lines.some(x=>!x.product||x.quantity>x.product.stock);function quantity(id,value){if(value<1)return;setCart(cart.map(x=>x.id===id?{...x,quantity:value}:x));}return <><PageHero title="سبد خرید شما" eyebrow="فروشگاه موثق"/>{submitted?<section className="container section narrow"><RequestFormPlaceholder/></section>:null}<section className="container section">{!cart.length&&!checkout?<Empty text="سبد خرید شما هنوز خالی است."><Button to="/store">دیدن محصولات</Button></Empty>:<div className="cart-layout"><div>{lines.map(({id,quantity:q,product:p})=><div className="cart-line" key={id}>{p&&<img src={p.image} alt={p.title}/>}<div><h3>{p?.title||'محصول حذف شده'}</h3><span>{money((p?.price||0)*q)} تومان</span>{p&&q>p.stock&&<p className="error-text">موجودی فعلی: {money(p.stock)}</p>}</div><div className="quantity"><button aria-label="کاهش تعداد" disabled={q<=1} onClick={()=>quantity(id,q-1)}><Minus size={15}/></button><span>{money(q)}</span><button aria-label="افزایش تعداد" disabled={!p||q>=p.stock} onClick={()=>quantity(id,q+1)}><Plus size={15}/></button></div><button className="icon-button" aria-label="حذف از سبد" onClick={()=>{setCart(cart.filter(x=>x.id!==id));setCheckout(false);}}><Trash2 size={18}/></button></div>)}{checkout&&<div className="form-panel"><h2>اطلاعات سفارش</h2><RequestForm kind="order" items={cart} onSuccess={()=>setCart([])}/></div>}</div><aside className="aside-box"><h3>خلاصه سفارش</h3><div className="summary-row"><span>مجموع محصولات</span><strong>{money(total)} تومان</strong></div><div className="summary-row"><span>هزینه ارسال</span><span>پس از هماهنگی</span></div><p className="muted tiny">این مبلغ اولیه است. قیمت نهایی پس از بررسی سفارش اعلام می‌شود.</p>{invalid&&<Notice type="error">موجودی سبد را اصلاح کنید.</Notice>}{!checkout&&<Button disabled={invalid||!cart.length} onClick={()=>setCheckout(true)}>ادامه و ثبت سفارش <ArrowUpLeft size={18}/></Button>}<Link className="text-link" to="/store">ادامه خرید</Link></aside></div>}</section></>;}
function RequestFormPlaceholder(){return null;}
