import {Link} from 'react-router-dom';
import {ArrowUpLeft,ShieldCheck,Building2,Cctv,House,Users,GraduationCap,Check,ArrowLeft,Clock3} from 'lucide-react';
export const icons={ShieldCheck,Building2,Cctv,House,Users,GraduationCap};
export function Icon({name='ShieldCheck',...props}){const Component=icons[name]||ShieldCheck;return <Component {...props}/>;}
export function Brand({light=false}){return <Link to="/" className={'brand '+(light?'brand-light':'')} aria-label="موثق، صفحه نخست"><span className="brand-symbol"><ShieldCheck size={35} strokeWidth={1.5}/></span><span><strong>موثق<span className="brand-dot">.</span></strong><small>موسسه حفاظتی مراقبتی</small></span></Link>;}
export function Button({to,children,variant='',className='',...props}){const cls=`button ${variant} ${className}`;return to?<Link className={cls} to={to} {...props}>{children}</Link>:<button className={cls} {...props}>{children}</button>;}
export function SectionHeading({eyebrow,title,text,to,link='مشاهده همه',light=false}){return <div className={'section-heading '+(light?'light':'')}><div><span className="eyebrow"><i/>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>{to&&<Link className="text-link" to={to}>{link}<ArrowLeft size={19}/></Link>}</div>;}
export function PageHero({title,eyebrow,description}){return <section className="page-hero"><div className="container"><div className="breadcrumbs"><Link to="/">صفحه نخست</Link><span>/</span><span>{eyebrow||title}</span></div><span className="eyebrow"><i/>{eyebrow||'موسسه موثق'}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div><ShieldCheck className="page-watermark"/></section>;}
export function ServiceCard({item,index=0}){return <Link to={'/services/'+item.id} className="service-card"><div className="card-photo"><img loading="lazy" src={item.image} alt={item.title}/><span className="photo-index">{String(index+1).padStart(2,'0')}</span></div><div className="service-content"><span className="icon-box"><Icon name={item.icon}/></span><h3>{item.title}</h3><p>{item.excerpt}</p><span className="card-link">بیشتر بدانید <ArrowUpLeft size={18}/></span></div></Link>;}
export function ArticleCard({item}){return <Link to={'/articles/'+item.id} className="article-card"><div className="card-photo"><img loading="lazy" src={item.image} alt={item.title}/><span className="image-tag">{item.category}</span></div><div className="article-body"><span className="muted tiny"><Clock3 size={14}/> خواندنی‌های موثق</span><h3>{item.title}</h3><p>{item.excerpt}</p><span className="card-link">مطالعه مطلب <ArrowLeft size={17}/></span></div></Link>;}
export function Empty({text='هنوز موردی منتشر نشده است.',children}){return <div className="empty"><ShieldCheck size={36}/><h3>{text}</h3>{children}</div>;}
export function Notice({children,type='info'}){return <div className={'notice '+type} role={type==='error'?'alert':'status'}>{children}</div>;}
export function CheckList({items}){return <ul className="check-list">{items.map(item=><li key={item}><span><Check size={15}/></span>{item}</li>)}</ul>;}
