import {useEffect} from 'react';
import {Routes,Route,useLocation,useParams} from 'react-router-dom';
import {Provider,useSite} from './context';
import {Header,Footer} from './components/Layout';
import Home from './pages/Home';
import Admin from './pages/Admin';
import {Services,Detail,StaticPage,Articles,Courses,CourseDetail,Contact,Regulations,Gallery,FAQ,Lookup,NotFound} from './pages/Content';
import {Store,ProductDetail,Cart} from './pages/Store';
function CustomPage(){const {id}=useParams();return <StaticPage slug={id}/>;}
function Site(){const {data,error,refresh}=useSite();const location=useLocation();const admin=location.pathname.startsWith('/admin');useEffect(()=>{document.title=(admin?'مدیریت موثق':'موثق | آرامش شما، مسئولیت ما');},[location.pathname]);if(admin)return <Admin/>;if(!data)return <div className="loading"><h2>موثق</h2><p>{error||'در حال آماده‌سازی...'}</p>{error&&<button onClick={refresh}>تلاش دوباره</button>}</div>;return <><a className="skip-link" href="#main">رفتن به محتوای اصلی</a><Header/><main id="main"><Routes><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:id" element={<Detail kind="services"/>}/><Route path="/courses" element={<Courses/>}/><Route path="/courses/:id" element={<CourseDetail/>}/><Route path="/store" element={<Store/>}/><Route path="/equipment" element={<Store/>}/><Route path="/store/:id" element={<ProductDetail/>}/><Route path="/cart" element={<Cart/>}/><Route path="/articles" element={<Articles/>}/><Route path="/news" element={<Articles news/>}/><Route path="/articles/:id" element={<Detail kind="posts"/>}/>{['about','director','activities','resume','privacy','terms'].map(slug=><Route path={'/'+slug} key={slug} element={<StaticPage slug={slug}/>}/>)}<Route path="/pages/:id" element={<CustomPage/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/licenses" element={<Gallery licenses/>}/><Route path="/regulations" element={<Regulations/>}/><Route path="/contact" element={<Contact/>}/><Route path="/consultation" element={<Contact consultation/>}/><Route path="/careers" element={<Contact career/>}/><Route path="/faq" element={<FAQ/>}/><Route path="/verify" element={<Lookup verify/>}/><Route path="/track" element={<Lookup/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></>;}
export default function App(){return <Provider><Site/></Provider>;}
